source 'https://cdn.cocoapods.org/'
source 'https://github.com/CocoaPods/Specs'

platform :ios, '13.0'

target 'UnityFramework' do
  pod 'Firebase/Analytics', '11.2.0'
  pod 'Firebase/Core', '11.2.0'
  pod 'Google-Mobile-Ads-SDK', '~> 11.11.0'
  pod 'GoogleUserMessagingPlatform', '2.6.0'
end
target 'Unity-iPhone' do
end
use_frameworks! :linkage => :static
